const PROPERTIES = [
  {
    id: 1,
    name: "One Commerce Plaza",
    type: "office",
    status: "For Lease",
    address: "1 Commerce Plaza, Financial District, NY 10004",
    price: "$58/sq ft/yr",
    size: "42,500",
    floors: "12 floors available",
    year: 2018,
    parking: "350 spaces",
    amenities: ["Concierge", "Fitness Center", "Conference Rooms", "Rooftop Terrace"],
    description: "Class A trophy tower in the heart of the Financial District. Floor-to-ceiling windows, LEED Gold certified, 24/7 security, and white-glove building management.",
    tag: "Featured",
    tagClass: "tag-featured",
    color: "#1a3c5e"
  },
  {
    id: 2,
    name: "Midtown Executive Center",
    type: "office",
    status: "For Sale",
    address: "555 Park Avenue, Midtown, NY 10022",
    price: "$18,500,000",
    size: "28,000",
    floors: "8 floors",
    year: 2015,
    parking: "180 spaces",
    amenities: ["Doorman", "Boardrooms", "Café", "High-Speed Fiber"],
    description: "Prestigious Park Avenue address offering column-free floor plates, stunning city views, and plug-and-play readiness for immediate occupancy.",
    tag: "For Sale",
    tagClass: "tag-sale",
    color: "#2d5a27"
  },
  {
    id: 3,
    name: "Westside Retail Row",
    type: "retail",
    status: "For Lease",
    address: "800 W 34th Street, Hudson Yards, NY 10001",
    price: "$125/sq ft/yr",
    size: "6,200",
    floors: "Ground floor",
    year: 2020,
    parking: "Public garage adjacent",
    amenities: ["Corner Exposure", "24-ft Ceilings", "Loading Dock", "Signage Rights"],
    description: "High-visibility corner retail with 80 feet of frontage on one of the city's busiest corridors. 45,000+ daily foot traffic. Ideal for restaurant, fitness, or flagship retail.",
    tag: "Hot",
    tagClass: "tag-hot",
    color: "#8b1a1a"
  },
  {
    id: 4,
    name: "Brooklyn Distribution Hub",
    type: "industrial",
    status: "For Lease",
    address: "2200 Atlantic Ave, Brooklyn, NY 11233",
    price: "$22/sq ft/yr",
    size: "85,000",
    floors: "Single story",
    year: 2019,
    parking: "100 truck bays",
    amenities: ["32-ft Clear Height", "Rail Access", "ESFR Sprinklers", "3-Phase Power"],
    description: "Modern last-mile distribution facility with direct highway access to I-278 and I-495. 32 dock doors, ESFR sprinkler system, and 200-amp 3-phase power throughout.",
    tag: "New",
    tagClass: "tag-new",
    color: "#4a3728"
  },
  {
    id: 5,
    name: "Tribeca Creative Lofts",
    type: "mixed",
    status: "For Lease",
    address: "320 Canal Street, Tribeca, NY 10013",
    price: "$72/sq ft/yr",
    size: "15,400",
    floors: "3 floors",
    year: 2017,
    parking: "Valet available",
    amenities: ["Exposed Brick", "Polished Concrete", "Skylights", "Private Courtyard"],
    description: "Iconic Tribeca loft building reborn as a creative campus. Original cast-iron facade, soaring 14-ft ceilings, and flexible floor plates perfect for media, tech, and creative agencies.",
    tag: "Featured",
    tagClass: "tag-featured",
    color: "#2c3e50"
  },
  {
    id: 6,
    name: "Queens Tech Campus",
    type: "office",
    status: "For Sale",
    address: "30-30 Northern Blvd, Long Island City, NY 11101",
    price: "$24,900,000",
    size: "54,000",
    floors: "6 floors",
    year: 2021,
    parking: "220 spaces",
    amenities: ["Data Center Ready", "Fiber Redundancy", "Collaboration Zones", "Bike Storage"],
    description: "State-of-the-art tech campus in Long Island City's booming innovation corridor. Designed for tech and life-science tenants with redundant power, raised floors, and generator backup.",
    tag: "New",
    tagClass: "tag-new",
    color: "#1a4a6e"
  },
  {
    id: 7,
    name: "Soho Flagship Storefront",
    type: "retail",
    status: "For Lease",
    address: "118 Spring Street, SoHo, NY 10012",
    price: "$350/sq ft/yr",
    size: "4,800",
    floors: "Ground + Basement",
    year: 2010,
    parking: "Street + public garages",
    amenities: ["Premium Signage", "High Ceilings", "Glass Facade", "Storage"],
    description: "Rare ground-floor opportunity on Spring Street in the heart of SoHo's most desirable retail block. Neighbors include global luxury and lifestyle brands. 50,000+ daily visitors.",
    tag: "Hot",
    tagClass: "tag-hot",
    color: "#6b2d5e"
  },
  {
    id: 8,
    name: "Bronx Industrial Park",
    type: "industrial",
    status: "For Lease",
    address: "1000 Hunts Point Ave, Bronx, NY 10474",
    price: "$18/sq ft/yr",
    size: "120,000",
    floors: "Single story",
    year: 2016,
    parking: "150 trailer spaces",
    amenities: ["40-ft Clear Height", "60 Dock Doors", "Cold Storage Option", "Security Gate"],
    description: "Massive cross-dock facility at Hunts Point — the tri-state area's premier food and logistics hub. Adjacent to the Hunts Point Produce Market with direct I-95 and Bruckner Expressway access.",
    tag: "For Lease",
    tagClass: "tag-lease",
    color: "#3d2b1f"
  },
  {
    id: 9,
    name: "Herald Square Retail",
    type: "retail",
    status: "For Lease",
    address: "34 West 34th Street, Midtown, NY 10001",
    price: "$280/sq ft/yr",
    size: "8,500",
    floors: "Ground Floor",
    year: 2008,
    parking: "Penn Station adjacent",
    amenities: ["Corner Position", "Macy's Proximity", "High Signage", "Storage"],
    description: "Ground-floor retail directly across from Macy's flagship store. Over 100,000 daily pedestrians. Previous tenant was a national restaurant chain — full white-box delivery available.",
    tag: "Featured",
    tagClass: "tag-featured",
    color: "#7a3b1e"
  },
  {
    id: 10,
    name: "Manhattan West Office",
    type: "office",
    status: "For Lease",
    address: "401 9th Avenue, Manhattan West, NY 10001",
    price: "$85/sq ft/yr",
    size: "33,000",
    floors: "5 contiguous floors",
    year: 2022,
    parking: "Garage available",
    amenities: ["Outdoor Terraces", "Floor-to-Ceiling Glass", "Smart Building Tech", "Bike Valet"],
    description: "Brand-new construction at Manhattan West — one of NYC's most exciting mixed-use developments. Stunning Hudson River views, wellness amenity floor, and direct access to the High Line.",
    tag: "New",
    tagClass: "tag-new",
    color: "#1e3a5f"
  },
  {
    id: 11,
    name: "Staten Island Flex Space",
    type: "industrial",
    status: "For Sale",
    address: "2000 Richmond Terrace, Staten Island, NY 10302",
    price: "$8,200,000",
    size: "38,000",
    floors: "2 floors",
    year: 2014,
    parking: "80 spaces",
    amenities: ["Office Buildout", "20-ft Clear Height", "Drive-in Doors", "Fenced Yard"],
    description: "Flex/office-warehouse combination ideal for light manufacturing, R&D, or distribution. Includes 8,000 sq ft of finished office space with private parking and secured yard.",
    tag: "For Sale",
    tagClass: "tag-sale",
    color: "#2e4a1e"
  },
  {
    id: 12,
    name: "Downtown Brooklyn Tower",
    type: "office",
    status: "For Lease",
    address: "1 Pierrepont Plaza, Downtown Brooklyn, NY 11201",
    price: "$55/sq ft/yr",
    size: "47,000",
    floors: "Floors 18–22",
    year: 2019,
    parking: "Building garage",
    amenities: ["Panoramic Views", "Full-Floor Plates", "Amenity Club", "24/7 Access"],
    description: "Downtown Brooklyn's premier office address offering full-floor suites on high floors with panoramic Manhattan Bridge and harbor views. Steps from all major subway lines.",
    tag: "Featured",
    tagClass: "tag-featured",
    color: "#1c3a5e"
  },
  {
    id: 13,
    name: "Flushing Commercial Center",
    type: "mixed",
    status: "For Sale",
    address: "136-20 Roosevelt Ave, Flushing, NY 11354",
    price: "$12,750,000",
    size: "22,000",
    floors: "4 floors",
    year: 2013,
    parking: "On-site + street",
    amenities: ["Retail Ground Floor", "Office Upper Floors", "Elevator", "Corner Location"],
    description: "Mixed-use investment property in the heart of Flushing's thriving commercial corridor. Strong existing tenancy, ground-floor retail, and three floors of office — stabilized cap rate of 5.8%.",
    tag: "For Sale",
    tagClass: "tag-sale",
    color: "#3a1e4e"
  },
  {
    id: 14,
    name: "Upper West Side Medical",
    type: "office",
    status: "For Lease",
    address: "2025 Broadway, Upper West Side, NY 10023",
    price: "$62/sq ft/yr",
    size: "9,800",
    floors: "Floor 4",
    year: 2011,
    parking: "Garages nearby",
    amenities: ["Medical Buildout", "Plumbing Throughout", "ADA Compliant", "Private Entrance"],
    description: "Fully built-out medical suite in an institutional-quality building on Broadway. Includes multiple exam rooms, waiting area, private staff entrance, and abundant natural light.",
    tag: "New",
    tagClass: "tag-new",
    color: "#1e4a3a"
  },
  {
    id: 15,
    name: "JFK Airport Cargo Center",
    type: "industrial",
    status: "For Lease",
    address: "150 Cargo Rd, Jamaica, NY 11430",
    price: "$30/sq ft/yr",
    size: "65,000",
    floors: "Single story",
    year: 2020,
    parking: "120 spaces + truck court",
    amenities: ["Airside Access", "USDA/CBP Inspected", "Cold Storage", "24-hr Security"],
    description: "Mission-critical air cargo facility with direct airside access at JFK. Includes 12,000 sq ft of temperature-controlled storage, USDA/CBP approved facility, and on-site customs processing.",
    tag: "Hot",
    tagClass: "tag-hot",
    color: "#3d2020"
  },
  {
    id: 16,
    name: "Chelsea Gallery District",
    type: "mixed",
    status: "For Lease",
    address: "529 W 20th Street, Chelsea, NY 10011",
    price: "$68/sq ft/yr",
    size: "11,200",
    floors: "Ground + Mezzanine",
    year: 2009,
    parking: "Hudson Yards garage",
    amenities: ["Gallery Lighting", "Polished Concrete", "Loading Lift", "High Line Access"],
    description: "Dramatic ground-floor and mezzanine space in Chelsea's iconic gallery district. Pin-spot gallery lighting, polished concrete floors, and a large freight lift. Steps from the High Line.",
    tag: "Featured",
    tagClass: "tag-featured",
    color: "#2a2a4a"
  },
  {
    id: 17,
    name: "East Village Neighborhood Retail",
    type: "retail",
    status: "For Lease",
    address: "105 2nd Avenue, East Village, NY 10003",
    price: "$95/sq ft/yr",
    size: "2,400",
    floors: "Ground Floor",
    year: 2005,
    parking: "Street parking",
    amenities: ["Exposed Brick", "Basement Storage", "Established Foot Traffic", "Signage"],
    description: "Intimate neighborhood retail on a vibrant East Village block. Ideal for boutique, café, or wellness concept. Exposed brick interior, cellar storage, and loyal local customer base.",
    tag: "For Lease",
    tagClass: "tag-lease",
    color: "#5a3020"
  },
  {
    id: 18,
    name: "Hudson Yards Innovation Hub",
    type: "office",
    status: "For Lease",
    address: "55 Hudson Yards, NY 10001",
    price: "$95/sq ft/yr",
    size: "61,000",
    floors: "Floors 30–32",
    year: 2023,
    parking: "Valet garage",
    amenities: ["Sky Lobby", "Wellness Floor", "Outdoor Terraces", "AI-Ready Infrastructure"],
    description: "Ultra-premium office space in Manhattan's newest landmark tower at 55 Hudson Yards. Trophy address, unobstructed Hudson River views, smart building systems, and world-class amenities.",
    tag: "New",
    tagClass: "tag-new",
    color: "#0d2a4a"
  },
  {
    id: 19,
    name: "Astoria Retail Corridor",
    type: "retail",
    status: "For Sale",
    address: "3012 Steinway Street, Astoria, NY 11103",
    price: "$3,800,000",
    size: "5,600",
    floors: "Ground Floor",
    year: 2007,
    parking: "On-site lot",
    amenities: ["Long-term Tenant", "NNN Lease", "Parking Lot", "Corner Exposure"],
    description: "Fully-tenanted NNN retail investment on Steinway Street — Astoria's premier commercial strip. Long-term national tenant with 7 years remaining on lease. Strong cap rate of 5.2%.",
    tag: "For Sale",
    tagClass: "tag-sale",
    color: "#3a2a1e"
  },
  {
    id: 20,
    name: "Harlem Business Center",
    type: "office",
    status: "For Lease",
    address: "125 W 125th Street, Harlem, NY 10027",
    price: "$42/sq ft/yr",
    size: "18,500",
    floors: "Floors 2–4",
    year: 2016,
    parking: "Adjacent garage",
    amenities: ["Renovated Lobby", "Fiber Internet", "Conference Center", "On-Site Management"],
    description: "Modern office space in Harlem's revitalized 125th Street corridor. Walking distance to the Apollo Theater, multiple subway lines, and a growing ecosystem of tech and media companies.",
    tag: "For Lease",
    tagClass: "tag-lease",
    color: "#1e3020"
  },
  {
    id: 21,
    name: "Financial District Co-working",
    type: "office",
    status: "For Lease",
    address: "80 Broad Street, FiDi, NY 10004",
    price: "$39/sq ft/yr",
    size: "24,000",
    floors: "Full floor",
    year: 2018,
    parking: "Building access",
    amenities: ["Plug & Play", "Shared Amenities", "Monthly Terms", "IT Infrastructure"],
    description: "Fully furnished, plug-and-play office floor ready for immediate occupancy. Flexible lease terms from 1 month. Includes reception, IT support, and access to shared conference rooms.",
    tag: "Hot",
    tagClass: "tag-hot",
    color: "#1a2a3a"
  },
  {
    id: 22,
    name: "Williamsburg Creative Campus",
    type: "mixed",
    status: "For Lease",
    address: "55 Water Street, Williamsburg, NY 11201",
    price: "$55/sq ft/yr",
    size: "32,000",
    floors: "4 floors",
    year: 2020,
    parking: "On-site + street",
    amenities: ["Rooftop Deck", "Event Space", "Bike Storage", "Freight Elevator"],
    description: "A converted warehouse reimagined as a modern creative campus. Raw industrial aesthetics with polished infrastructure — exposed steel, 12-ft ceilings, a 4,000 sq ft rooftop deck, and event space.",
    tag: "Featured",
    tagClass: "tag-featured",
    color: "#2a1a3a"
  },
  {
    id: 23,
    name: "Newark Distribution Center",
    type: "industrial",
    status: "For Sale",
    address: "500 Port Street, Newark, NJ 07105",
    price: "$31,500,000",
    size: "200,000",
    floors: "Single story",
    year: 2017,
    parking: "200 trailer positions",
    amenities: ["Port Access", "Class I Rail", "80 Dock Doors", "ESFR Sprinklers"],
    description: "Institutional-grade distribution center adjacent to Port Newark-Elizabeth Marine Terminal. Premier logistics location with direct port, rail, and highway access — fully leased with long-term tenant.",
    tag: "For Sale",
    tagClass: "tag-sale",
    color: "#2e2010"
  },
  {
    id: 24,
    name: "Flatiron Tech Loft",
    type: "office",
    status: "For Lease",
    address: "902 Broadway, Flatiron, NY 10010",
    price: "$74/sq ft/yr",
    size: "12,000",
    floors: "Full floor",
    year: 2015,
    parking: "Nearby garages",
    amenities: ["Exposed Beams", "Historic Building", "2 Terraces", "Fiber"],
    description: "Historic loft-style office in an iconic Flatiron district building. Original exposed beams and columns, two private outdoor terraces, and abundant natural light from four exposures.",
    tag: "New",
    tagClass: "tag-new",
    color: "#1e2a3a"
  },
  {
    id: 25,
    name: "Fifth Avenue Street-Level",
    type: "retail",
    status: "For Lease",
    address: "620 Fifth Avenue, Rockefeller Center, NY 10020",
    price: "$500/sq ft/yr",
    size: "3,200",
    floors: "Ground Floor",
    year: 2000,
    parking: "Rockefeller Center access",
    amenities: ["5th Ave Frontage", "Luxury Neighbors", "High Ceilings", "Premium Signage"],
    description: "Extraordinary opportunity on global retail's most iconic address — Fifth Avenue at Rockefeller Center. Neighbors include Saks Fifth Avenue, Tiffany & Co., and other world-class brands.",
    tag: "Hot",
    tagClass: "tag-hot",
    color: "#7a1a2a"
  },
  {
    id: 26,
    name: "Long Island Suburban Office",
    type: "office",
    status: "For Sale",
    address: "990 Stewart Avenue, Garden City, NY 11530",
    price: "$14,200,000",
    size: "36,000",
    floors: "3 floors",
    year: 2012,
    parking: "250 surface spaces",
    amenities: ["Campus Setting", "Cafeteria", "Training Rooms", "EV Charging"],
    description: "Suburban campus-style office building on Long Island's Gold Coast. Abundant free parking, full cafeteria, multiple conference and training rooms — ideal corporate headquarters.",
    tag: "For Sale",
    tagClass: "tag-sale",
    color: "#1e3a2a"
  },
  {
    id: 27,
    name: "Bushwick Artist Studios",
    type: "mixed",
    status: "For Lease",
    address: "1083 Flushing Ave, Bushwick, NY 11237",
    price: "$35/sq ft/yr",
    size: "18,000",
    floors: "3 floors",
    year: 2018,
    parking: "Street + lot",
    amenities: ["Raw Space", "High Ceilings", "Natural Light", "Freight Access"],
    description: "Raw industrial building in Bushwick's vibrant arts district. Three floors of flexible space with 14-ft ceilings, oversized windows, and freight access — perfect for studios, production, and creative use.",
    tag: "For Lease",
    tagClass: "tag-lease",
    color: "#2a1e1e"
  },
  {
    id: 28,
    name: "Secaucus Warehouse",
    type: "industrial",
    status: "For Lease",
    address: "400 Meadowland Pkwy, Secaucus, NJ 07094",
    price: "$20/sq ft/yr",
    size: "95,000",
    floors: "Single story",
    year: 2015,
    parking: "90 trailer positions",
    amenities: ["36-ft Clear Height", "50 Dock Doors", "Cross-Dock Design", "Generator"],
    description: "Cross-dock warehouse in the heart of the Meadowlands. 36-ft clear height, 50 dock-high doors (25 per side), in-place generator system, and under 5 miles from the Lincoln Tunnel.",
    tag: "For Lease",
    tagClass: "tag-lease",
    color: "#302010"
  },
  {
    id: 29,
    name: "Upper East Side Medical Plaza",
    type: "office",
    status: "For Sale",
    address: "425 E 61st Street, Upper East Side, NY 10065",
    price: "$19,800,000",
    size: "21,000",
    floors: "5 floors",
    year: 2014,
    parking: "On-site garage",
    amenities: ["Medical Use", "All Plumbing", "Imaging Suite", "Pharmacy Space"],
    description: "Fully built-out medical office building one block from New York-Presbyterian Hospital. Complete clinical infrastructure including imaging-ready space, procedure rooms, and pharmacy.",
    tag: "For Sale",
    tagClass: "tag-sale",
    color: "#1e3a3a"
  },
  {
    id: 30,
    name: "Times Square Retail Flagship",
    type: "retail",
    status: "For Lease",
    address: "1500 Broadway, Times Square, NY 10036",
    price: "$750/sq ft/yr",
    size: "10,000",
    floors: "Ground + Mezzanine",
    year: 2022,
    parking: "Multiple garages",
    amenities: ["LED Signage", "50M Annual Visitors", "Double-Height", "Basement"],
    description: "Once-in-a-generation retail flagship in the heart of Times Square. Double-height storefront with LED signage rights facing 50 million annual visitors. The ultimate brand visibility platform.",
    tag: "Hot",
    tagClass: "tag-hot",
    color: "#4a0a0a"
  }
];
